#include "TTree.h"
#include "TFile.h"
#include "TFile.h"
#include "TTree.h"
#include "TLeaf.h"
#include "TEntryList.h"
#include <iostream>

void copytree3() {
// Example of Root macro to copy a subset of a Tree to a new Tree
// Only selected entries are copied to the new Tree.
// The input file has been generated by the program in $ROOTSYS/test/Event
// with   Event 1000 1 99 1
//Author: Rene Brun
   
   //gSystem->Load("$ROOTSYS/test/libEvent");

   //Get old file, old tree and set top branch address
   TFile *oldfile = new TFile("r0327356667_v120_merit.root");
   TTree *oldtree = (TTree*)oldfile->Get("MeritTuple");   
   
   //Disable all branches and reenable only the needed ones
   UInt_t eventId;
   UInt_t eventRun;
   oldtree->SetBranchStatus("*",0);
   oldtree->SetBranchStatus("Evt*",1);
   oldtree->SetBranchAddress("EvtEventId",&eventId);
   oldtree->SetBranchAddress("EvtRun",&eventRun);
   Int_t nentries = (Int_t)oldtree->GetEntries();
   
   //Create a new file + a clone of old tree in new file
   TFile *newfile = new TFile("r0327356667_v001_merit_reduced.root","recreate");
   TTree *newtree = oldtree->CloneTree(0);

   for (Int_t i=0;i<nentries; i++) {      
      oldtree->GetEntry(i);
      if (eventId < 100000) continue;
      if (eventId > 700000) break;
      if (eventId != 199996 && 
          (eventId <= 300544 ||
          eventId >= 300858) && 
          eventId != 200031 ) 
          { 
            std::cerr << ".";
            newtree->Fill();
          }
      
   }
   newtree->Print();
   newtree->AutoSave();
   delete oldfile;
   delete newfile;
}

